### ISSUE TITLE
OneSignalPrefs$WritePrefHandlerThread.startDelayedWrite crash

### ISSUE THREAD

**Issue by RedMaus** [OneSignal/OneSignal-Unity-SDK#261]
Hello! After installation OneSignal package we have some crashes from google play console:

Environment:
1. OneSignal version:2.11.0
2. Unity version:2018.4.10f1
3. occurs only on Android 9.0

Steps to Reproduce Issue:
Unable to recreate this issue. 

Stacktrace:
  at java.lang.Thread.start (Thread.java:724)
  at com.onesignal.OneSignalPrefs$WritePrefHandlerThread.startDelayedWrite (OneSignalPrefs.java:117)
  at com.onesignal.OneSignalPrefs.startDelayedWrite (OneSignalPrefs.java:183)
  at com.onesignal.OneSignal.setAppContext (OneSignal.java:601)
  at com.onesignal.RestoreKickoffJobService.startProcessing (RestoreKickoffJobService.java:15)
  at com.onesignal.OneSignalJobServiceBase$1.run (OneSignalJobServiceBase.java:22)
  at java.lang.Thread.run (Thread.java:764)

**Comment by vforvasile** [comment]
Duplicate of [https://github.com/OneSignal/OneSignal-Android-SDK/issues/917](url)

**Comment by fsener** [comment]
We also have this crash and it occurs on Android 9 mostly (91%) but not necessarily.

**Comment by RedMaus** [comment]
> We also have this crash and it occurs on Android 9 mostly (91%) but not necessarily.

Any ideas how to fix it? Or what can be reason of this problem?

**Comment by fsener** [comment]
> > We also have this crash and it occurs on Android 9 mostly (91%) but not necessarily.
> 
> Any ideas how to fix it? Or what can be reason of this problem?

No to be honest, I'm waiting an update on OneSignal's end.

**Comment by jkasten2** [comment]
@RedMaus @fsener Thanks for reporting the crash. I believe this is the same issue as https://github.com/OneSignal/OneSignal-Android-SDK/issues/917 based on the stack trace.

**Comment by jkasten2** [comment]
This should now be fixed with OneSignal-Unity-SDK 2.11.3
https://github.com/OneSignal/OneSignal-Unity-SDK/releases

**Comment by fsener** [comment]
This problem still occurs even after 2.11.3 and 2.11.4 updates.

**Comment by fsener** [comment]
Any updated on this issue?

**Comment by RedMaus** [comment]
we have not updated onesignal yet

чт, 12 мар. 2020 г. в 08:59, Ferhat Şener <notifications@github.com>:

**Comment by fsener** [comment]
@RedMaus Still happens on the latest version 2.12.0

**Comment by jackatfp** [comment]
the bug is not fixed.

com.onesignal.OneSignalPrefs$WritePrefHandlerThread.startThread (OneSignalPrefs.java:174)
com.onesignal.OneSignalPrefs$WritePrefHandlerThread.startDelayedWrite (OneSignalPrefs.java:137)
com.onesignal.OneSignalPrefs.startDelayedWrite (OneSignalPrefs.java:238)
com.onesignal.OneSignalPrefs.save (OneSignalPrefs.java:270)
com.onesignal.OneSignalPrefs.saveLong (OneSignalPrefs.java:258)
com.onesignal.LocationGMS.setLastLocationTime (LocationGMS.java:113)
com.onesignal.LocationGMS.fireComplete (LocationGMS.java:330)
com.onesignal.LocationGMS.fireFailedComplete (LocationGMS.java:303)
com.onesignal.LocationGMS.getLocation (LocationGMS.java:227)
com.onesignal.OneSignalSyncServiceUtils$SyncRunnable.run (OneSignalSyncServiceUtils.java:233)

**Comment by ikitae** [comment]
in 2.12.2

com.onesignal.OneSignalPrefs$WritePrefHandlerThread.startThread (OneSignalPrefs.java:201)
com.onesignal.OneSignalPrefs$WritePrefHandlerThread.startDelayedWrite (OneSignalPrefs.java:142)
com.onesignal.OneSignalPrefs$WritePrefHandlerThread.access$200 (OneSignalPrefs.java:125)
com.onesignal.OneSignalPrefs.startDelayedWrite (OneSignalPrefs.java:282)
com.onesignal.OneSignal.setAppContext (OneSignal.java:607)
com.onesignal.OneSignalSyncServiceUtils.doBackgroundSync (OneSignalSyncServiceUtils.java:178)
com.onesignal.SyncJobService.onStartJob (SyncJobService.java:40)
android.app.job.JobService$1.onStartJob (JobService.java:62)
android.app.job.JobServiceEngine$JobHandler.handleMessage (JobServiceEngine.java:108)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7078)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
